# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='username', max_length=30),
        ),
    ]
