# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
