# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-01 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
