# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-26 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Ordered',
            new_name='ProductOrdered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
